server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
#  zipkin:
#    base-url: http://localhost:9411
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://45.76.76.18:3306/xxxaaa?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: xxxaaa
#    password: slkf813ijasdoyasdk12

#  sleuth:
#    sampler:
#      probability: 1 #采样率 1为全部采集
#
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.ms.springcloud.model


eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}-8002
    prefer-ip-address: true  #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 1  #向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 90 #收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除